### PR TITLE
Upgrading the traceenricher libraries and others to latest versions.

### PR DESCRIPTION
**Pull request by buchi-busireddy**
Trace enricher libraries bring in a bug fix in showing the URL properly in the traces tab and also in explorer URL column. 
While at it, i've upgraded other libraries to bring them to the latest.

### CODE REVIEW

**Comment by tim-mwangi** [comment]
@buchi-busireddy what do you want to do about snyk-scan?

**Comment by buchi-busireddy** [comment]
> @buchi-busireddy what do you want to do about snyk-scan?

I'll fix that. Give me some time.

**Comment by tim-mwangi** [comment]
> > @buchi-busireddy what do you want to do about snyk-scan?
> 
> I'll fix that. Give me some time.

This could still go in and the fix can be put in later. But no rush.

**Review by tim-mwangi — DISMISSED** [review]

**Comment by tim-mwangi** [comment]
@buchi-busireddy failing on guava

**Comment by buchi-busireddy** [comment]
> @buchi-busireddy failing on guava

Waiting on https://github.com/hypertrace/view-generator-framework/pull/18 to be merged first.

**Comment by kotharironak** [comment]
@buchi-busireddy As part of consolidating repo's in PR - https://github.com/hypertrace/hypertrace-ingester/pull/15, closing this for now.
we will have to report after the merge of - https://github.com/hypertrace/hypertrace-ingester/pull/15. will work with you.

**Pull request closed without merging**
